name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        bash run_tests.bash

  safety-sca:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - uses: pyupio/safety@2.3.4
      id: scan-1
      continue-on-error: true
      with:
        api-key: ${{secrets.SAFETY_API_KEY}}
        scan: 'env'
        
    - if: steps.scan-1.outcome != 'failure'
      run: echo 'Safety failed to run, but the next step in the pipeline continued.' && exit 1

  bandit-sast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      # this config almost works. ALMOST.
      # creates comment in PR but results are wrong - no vuln detected
      # uses: shundor/python-bandit-scan@v1.0
      # with: 
      #   path: "."
      #   level: medium
      #   confidence: medium

      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install bandit and run
      run: |
        python -m pip install bandit
        python -m bandit app.py

  zap-dast:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup uvicorn app
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m uvicorn app:app --port 8000 --host 0.0.0.0 &
    - name: Wait for uvicorn to start
      run: sleep 4
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.8.0
      with:
        target: http://localhost:8000/get-result
    # - name: Stop uvicorn
    #   run: pkill uvicorn



  code-pep-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."


  final-build:
    runs-on: ubuntu-latest
    needs: [safety-sca, bandit-sast, zap-dast, code-pep-format]
    steps:
      - uses: actions/checkout@v3
      - name: Build docker images
        run: docker build -t beta .









